import type { AppState, AgentId, AgentStatus, CarryItem, SkillProposal, SkillRule, Reviewer, Story, Gate, Run, SpecFile, QualityItem } from './types'

// ─── Project ──────────────────────────────────────────────────────────────────

export function selectProject(state: AppState) {
  return state.project
}

// ─── Agent statuses (derived from active runs + open gates) ───────────────────

export function selectAgentStatus(state: AppState, agent: AgentId): AgentStatus {
  const hasActiveRun = state.runs.some(r => r.agent === agent && r.status === 'running')
  if (hasActiveRun) return 'running'

  // 'flow' is blocked while any gate is open
  if (agent === 'flow') {
    const anyOpen = state.gates.some(g => g.status === 'open')
    if (anyOpen) return 'blocked'
  }

  // Agent is 'running' if stories are currently in its stage
  const stageMap: Record<AgentId, string[]> = {
    onboarding: ['backlog'],
    ba:         ['requirements'],
    dev:        ['plan', 'build'],
    qa:         ['test'],
    flow:       [],
  }
  const inStage = state.stories.some(s => stageMap[agent].includes(s.stage))
  if (inStage) return 'running'

  return 'idle'
}

// ─── Stories ──────────────────────────────────────────────────────────────────

export function selectStory(state: AppState, key: string): Story | undefined {
  return state.stories.find(s => s.key === key)
}

// Chain trail: derives 4 chips (REQ → PLAN → DIFF → TESTS) from story stage
export function selectChainTrail(state: AppState, storyKey: string) {
  const story = state.stories.find(s => s.key === storyKey)
  if (!story) return []

  const stageOrder: Record<string, number> = {
    backlog: -1, requirements: 0, plan: 1, build: 2, test: 3, accept: 4, done: 5,
  }
  const idx = stageOrder[story.stage] ?? -1

  const plan = story.artifacts.plan
  const diff = story.artifacts.diff

  const chips = [
    {
      type: 'REQ', label: 'Requirement', id: story.key,
      textColor: '#1D4ED8', bg: '#EFF6FF', accent: '#3B82F6',
      summary: story.title,
      linkStatus: idx > 0 ? 'done' : idx === 0 ? 'current' : 'pending',
    },
    {
      type: 'PLAN', label: 'Plan', id: plan?.id ?? '—',
      textColor: '#6D28D9', bg: '#F5F3FF', accent: '#8B5CF6',
      summary: plan ? `${story.title} · rev ${plan.revisions.length} of ${plan.revisions.length}` : 'Not yet generated',
      linkStatus: idx > 1 ? 'done' : idx === 1 ? 'current' : 'pending',
    },
    {
      type: 'DIFF', label: 'Diff', id: diff?.mr ?? '—',
      textColor: '#C2410C', bg: '#FFF7ED', accent: '#F97316',
      summary: diff
        ? `MR ${diff.mr}: feat/${storyKey.toLowerCase()} → main · ${diff.hunks} hunks · +${diff.additions} −${diff.deletions}`
        : 'Not yet generated — awaiting plan approval',
      linkStatus: idx > 2 ? 'done' : idx === 2 ? 'current' : 'pending',
    },
    {
      type: 'TESTS', label: 'Tests', id: 'SPEC-' + storyKey.split('-')[1],
      textColor: '#15803D', bg: '#F0FDF4', accent: '#16A34A',
      summary: story.artifacts.tests
        ? `Specs generated by QA agent · skill v2`
        : 'Not yet generated — awaiting diff',
      linkStatus: idx > 3 ? 'done' : idx === 3 ? 'current' : 'pending',
    },
  ] as const

  return chips
}

// ─── Gates ────────────────────────────────────────────────────────────────────

export function selectGatesForAgent(state: AppState, agent: AgentId): Gate[] {
  return state.gates.filter(g => g.agent === agent)
}

export function selectOpenGatesForAgent(state: AppState, agent: AgentId): Gate[] {
  return state.gates.filter(g => g.agent === agent && g.status === 'open')
}

export function selectGate(state: AppState, gateId: string): Gate | undefined {
  return state.gates.find(g => g.id === gateId)
}

// Map open gates for a given agent into queue row format, sorted by openedAt descending
export function selectGateQueue(state: AppState, agent: AgentId) {
  const agentGates = state.gates.filter(g => g.agent === agent && g.status === 'open')

  return agentGates.map(gate => {
    const story = state.stories.find(s => s.key === gate.storyKey)

    // Compute "waiting" from openedAt — simplified: use a static offset for the prototype
    const waitingMap: Record<string, string> = {
      'G-02': '1h 12m', 'G-03': '1d 2h',
      'G-04': '2h 11m', 'G-05': '4h 20m', 'G-06': '2d 1h',
    }

    // Story is 'stale' if waiting > 24h (gate ids G-03 and G-06 are stale)
    const isStale = gate.id === 'G-03' || gate.id === 'G-06'

    return {
      key:         gate.storyKey,
      gateId:      gate.id,
      title:       story?.title ?? gate.storyKey,
      assignee:    story?.assignee ?? '—',
      waiting:     waitingMap[gate.id] ?? '—',
      status:      (isStale ? 'stale' : 'pending') as 'pending' | 'stale',
      gateRole:    gate.role,
      submittedBy: story?.submittedBy ?? null,
    }
  })
}

// ─── Runs ─────────────────────────────────────────────────────────────────────

export function selectRun(state: AppState, storyKey: string, agent: AgentId): Run | undefined {
  return state.runs.find(r => r.storyKey === storyKey && r.agent === agent)
}

// Tokens used by an agent on a story
export function selectTokensUsed(state: AppState, storyKey: string, agent: AgentId): number {
  return selectRun(state, storyKey, agent)?.tokensUsed ?? 0
}

// ─── Tests (QA) ───────────────────────────────────────────────────────────────

export function selectSpecs(state: AppState, storyKey: string): SpecFile[] {
  return selectStory(state, storyKey)?.artifacts.tests?.specs ?? []
}

export function selectTestQuality(state: AppState, storyKey: string): QualityItem[] {
  return selectStory(state, storyKey)?.artifacts.tests?.quality ?? []
}

// Summary counts derived from spec cases
export function selectTestSummary(state: AppState, storyKey: string) {
  const specs = selectSpecs(state, storyKey)
  const cases = specs.flatMap(f => f.cases)
  return {
    pass:    cases.filter(c => c.result === 'pass').length,
    fail:    cases.filter(c => c.result === 'fail').length,
    total:   cases.length,
  }
}

// ─── Plan (Dev) ───────────────────────────────────────────────────────────────

export function selectPlan(state: AppState, storyKey: string) {
  return selectStory(state, storyKey)?.artifacts.plan ?? null
}

export function selectImpactMap(state: AppState, storyKey: string) {
  return selectStory(state, storyKey)?.artifacts.impactMap ?? null
}

export function selectPlanQuality(state: AppState, storyKey: string): QualityItem[] {
  return selectStory(state, storyKey)?.artifacts.plan?.quality ?? []
}

// Dev sprint summary stats — derived from runs
export function selectDevSprintStats(state: AppState) {
  const devRuns = state.runs.filter(r => r.agent === 'dev' && r.status === 'done')
  const totalRuns = devRuns.length
  const avgRevisions = totalRuns > 0
    ? (devRuns.reduce((acc, r) => {
        const story = state.stories.find(s => s.key === r.storyKey)
        return acc + (story?.artifacts.plan?.revisions.length ?? 1)
      }, 0) / totalRuns).toFixed(1)
    : '—'

  const minutesPerRun = devRuns
    .map(r => {
      const story = state.stories.find(s => s.key === r.storyKey)
      return story?.stageMinutes.plan ?? 0
    })
    .filter(m => m > 0)
  const avgMinutes = minutesPerRun.length > 0
    ? Math.round(minutesPerRun.reduce((a, b) => a + b, 0) / minutesPerRun.length)
    : 0

  return [
    { label: 'Runs this sprint',    value: String(totalRuns),          sub: `${totalRuns} plans generated` },
    { label: 'Plan iterations avg', value: avgRevisions,               sub: 'corrections per run'          },
    { label: 'Avg run time',        value: avgMinutes ? `${avgMinutes} min` : '—', sub: '↓ 6 min vs prev' },
    { label: 'Drift flags',         value: '0',                        sub: 'this sprint'                  },
  ]
}

// ─── Skill versions (Onboarding) ─────────────────────────────────────────────

export function selectOnboardingSkill(state: AppState) {
  return state.skillVersions.find(sv => sv.agent === 'onboarding')
}

export function selectRules(state: AppState): SkillRule[] {
  return selectOnboardingSkill(state)?.rules ?? []
}

export function selectReviewers(state: AppState): Reviewer[] {
  return selectOnboardingSkill(state)?.reviewers ?? []
}

// ─── Flow analytics ───────────────────────────────────────────────────────────

export function selectStageTimeline(state: AppState, storyKey: string) {
  const story = state.stories.find(s => s.key === storyKey)
  if (!story) return []

  const stages = [
    { name: 'Onboard',      stageKey: 'backlog'       as const, display: (m: number) => `${m} min` },
    { name: 'Requirements', stageKey: 'requirements'  as const, display: (m: number) => m >= 60 ? `${(m/60).toFixed(1)} h` : `${m} min` },
    { name: 'Plan',         stageKey: 'plan'          as const, display: (m: number) => m >= 60 ? `${(m/60).toFixed(1)} h` : `${m} min` },
    { name: 'Build',        stageKey: 'build'         as const, display: (m: number) => m >= 60 ? `${(m/60).toFixed(1)} h` : `${m} min` },
    { name: 'Test',         stageKey: 'test'          as const, display: (m: number) => m >= 60 ? `${(m/60).toFixed(1)} h` : `${m} min` },
  ]

  const stageOrder: Record<string, number> = {
    backlog: -1, requirements: 0, plan: 1, build: 2, test: 3, accept: 4, done: 5,
  }
  const storyIdx = stageOrder[story.stage] ?? -1

  const result = stages.map(s => {
    const minutes = story.stageMinutes[s.stageKey]
    const stageIdx = stageOrder[s.stageKey] ?? -1
    const pending = stageIdx > storyIdx || minutes == null
    return {
      name: s.name,
      display: minutes != null ? s.display(minutes) : 'next day',
      units: minutes ?? 26,
      pending,
    }
  })

  // Add Accept as always-pending if story isn't done/accept
  const acceptPending = story.stage !== 'done' && story.stage !== 'accept'
  result.push({ name: 'Accept', display: 'next day', units: 26, pending: acceptPending })

  return result
}

export function selectStoryComparison(state: AppState, s1Key: string, s2Key: string) {
  const s1 = state.stories.find(s => s.key === s1Key)
  const s2 = state.stories.find(s => s.key === s2Key)
  if (!s1 || !s2) return []

  const cycleTime = (story: typeof s1) => {
    const mins = Object.values(story.stageMinutes).reduce<number>((a, b) => a + (b ?? 0), 0)
    return (mins / (60 * 8)).toFixed(1) + ' d'  // assume 8h days
  }

  const tokens = (storyKey: string) => {
    const t = state.runs.filter(r => r.storyKey === storyKey).reduce((a, r) => a + r.tokensUsed, 0)
    return t >= 1000 ? `${(t / 1000).toFixed(1)}k` : String(t)
  }

  const archTouches = (storyKey: string) => {
    return state.gates.filter(g => g.storyKey === storyKey && g.role === 'ba').length
  }

  const driftFlags = (story: typeof s1) => {
    const specs = story.artifacts.tests?.specs.flatMap(f => f.cases) ?? []
    return specs.filter(c => c.result === 'fail').length
  }

  const planRevisions = (story: typeof s1) => story.artifacts.plan?.revisions.length ?? 1

  return [
    { label: 'Plan iterations',   s1: String(planRevisions(s1)), s2: String(planRevisions(s2)), direction: 'down' as const, better: 'down' as const },
    { label: 'Cycle time',        s1: cycleTime(s1),             s2: cycleTime(s2),             direction: 'down' as const, better: 'down' as const },
    { label: 'Tokens',            s1: tokens(s1Key),             s2: tokens(s2Key),             direction: 'down' as const, better: 'down' as const },
    { label: 'Architect touches', s1: String(archTouches(s1Key)), s2: String(archTouches(s2Key)), direction: 'down' as const, better: 'down' as const },
    { label: 'Drift flags',       s1: String(driftFlags(s1)),    s2: String(driftFlags(s2)),    direction: 'down' as const, better: 'down' as const },
  ]
}

export function selectCarryForward(state: AppState): CarryItem[] {
  return state.carryForward
}

export function selectProposals(state: AppState): SkillProposal[] {
  return state.skillVersions.flatMap(sv => sv.proposals)
}
